services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
      POSTGRES_DB: ${LOCAL_DB}

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      LOCAL_DB_USER: ${LOCAL_DB_USER}
      LOCAL_DB_PASSWORD: ${LOCAL_DB_PASSWORD}
      LOCAL_DB: ${LOCAL_DB}
    ports:
      - 8080:8080